services:
  - type: web
    name: myai-backend
    env: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEYS
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: personal_ai
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ORIGINS
        value: https://myai-frontend.onrender.com

  - type: web
    name: myai-frontend
    env: static
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        # Point to the backend service URL on Render after first deploy, e.g. https://myai-backend.onrender.com
        value: https://myai-backend.onrender.com
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

